version: '2'
services:
    cloud-server:
        image: "hubot/new-cloud-server"
        restart: 'always'
        environment:
            - PG_HOST=postgres
            - PG_USER=hubot
            - PG_PASS=hubot
            - PG_DATABASE=hubot
        ports:
            - "3008:3000"

    postgres:
      image: "postgres"
      restart: always
      volumes:
       - ./postgres_data:/var/lib/postgresql/data
      ports:
        - "5432:5432"
      environment:
        - POSTGRES_PASSWORD=hubot
        - POSTGRES_USER=hubot

